### ISSUE TITLE
No parameter with name "append" found to set (mnHomeologPhase).

### ISSUE THREAD

**Issue by arzwa** [wf8/homologizer#1]
Hi Will, I was trying homologizer on some data of mine, everything works fine, except that I cannot add the phase monitors. I get the following error:
```
> for (i in 1:num_loci){            
+     log_file = output_file + "_locus_" + i + "_phase.log"
+     monitors[++mni] = mnHomeologPhase(filename=log_file, printgen=1, ctmc[i])
+ }
   Error:       No parameter with name "append" found to set.
```
My experience with `Rev` is quite limited, and I couldn't really figure out what this means. Turns out this also breaks in your example analysis in `cystopteridaceae.Rev`. (I'm able to sample from the posterior and obtain the posterior for the MUL tree. When I previously tested homologizer, I must have missed that I wasn't monitoring the sampler for the phases of individual loci).

**Comment by arzwa** [comment]
I was working with the `development` branch of RevBayes. It seems the monitor appears to work fine with the `master` branch of RevBayes. (Note that, for some reason, the documentation on the RevBayes website suggests compiling from the `development` branch).

**Comment by wf8** [comment]
Hi Arthur, sorry for this problem! The development branch is the bleeding
edge where new functionality is merged from different developers, which
sometimes breaks things. Would one of the pre-compiled executables work for
you? https://revbayes.github.io/download

**Comment by arzwa** [comment]
Well, I'm on Linux and don't have singularity installed, so I compiled from source following https://revbayes.github.io/compile-linux (which instructs to use the dev branch). Anyway, now I'm on master and its working fine so no worries :).
